# Generated by Django 5.2.6 on 2026-06-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_alter_feedback_remetente_alter_feedback_risco_ia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='mensagem_original',
            new_name='mensagem',
        ),
    ]
