# Generated by Django 5.2.6 on 2026-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_rename_mensagem_original_feedback_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='hash_conteudo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
